plugin:
    type: plugin
    name: Discuss
    description: |
        Disqus integration for your shop
    fa_icon: comment-o
    fields:
        disqus_identifier:
            type: text
            label: elcodi_plugin.disqus.disqus_identifier
        disqus_enabled_product:
            type: checkbox
            label: elcodi_plugin.disqus.disqus_enabled_product
        disqus_enabled_blog_post:
            type: checkbox
            label: elcodi_plugin.disqus.disqus_enabled_blog_post
